name: Tweet every 20 seconds

on:
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  tweet:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Tweepy
        run: pip install tweepy

      - name: Run tweet loop (3x every 20s)
        run: |
          for i in 1 2 3
          do
            python tweet.py
            sleep 20
          done
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
